### ISSUE TITLE
Hide "save and view AMP page button"

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#10]
If possible, @hadfieldjoe would like this button to be hidden from content creators when they create a story. Does this require making a subtheme of adminimal just to hide that button?

**Comment by blakemorgan** [comment]
The module is said to be feature complete, so do we just want to take the form button out of the code? If not, I'll need help figuring out how to install the amp library so we can just use a custom module without composer.

**Comment by katrialesser** [comment]
Go ahead and make a subtheme of adminimal
