### ISSUE TITLE
Some stories have fid image tokens inside a story

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#104]
- [x] check how many there are in db -  101
- [ ] could get the images via the fid from the old site and put them in
- [ ] or could remove the code
- [ ] or could manually fix the recent ones if there are few enough with this issue

**Comment by sher1** [comment]
Here are the node id's
+-----------+
| entity_id |
+-----------+
|     10289 |
|     10740 |
|     10770 |
|     10799 |
|     10800 |
|     10854 |
|     10864 |
|     10882 |
|     10939 |
|     10998 |
|     10999 |
|     11005 |
|     11012 |
|     11019 |
|     11020 |
|     11032 |
|     11036 |
|     11043 |
|     11046 |
|     11054 |
|     11057 |
|     11058 |
|     11060 |
|     11061 |
|     11068 |
|     11073 |
|     11078 |
|     11079 |
|     11108 |
|     11109 |
|     11113 |
|     11118 |
|     11128 |
|     11130 |
|     11159 |
|     11161 |
|     11165 |
|     11178 |
|     11182 |
|     11185 |
|     11187 |
|     11193 |
|     11199 |
|     11209 |
|     11227 |
|     11228 |
|     11229 |
|     11233 |
|     11239 |
|     11240 |
|     11241 |
|     11245 |
|     11246 |
|     11247 |
|     11249 |
|     11252 |
|     11255 |
|     11260 |
|     11262 |
|     11317 |
|     11352 |
|     11363 |
|     11367 |
|     11369 |
|     11370 |
|     11375 |
|     11376 |
|     11377 |
|     11378 |
|     11380 |
|     11395 |
|     11399 |
|     11402 |
|     11412 |
|     11414 |
|     11435 |
|     11454 |
|     11455 |
|     11457 |
|     11466 |
|     11469 |
|     11476 |
|     11480 |
|     11481 |
|     11484 |
|     11485 |
|     11493 |
|     11494 |
|     11503 |
|     11504 |
|     11506 |
|     11512 |
|     11515 |
|     11526 |
|     11530 |
|     11536 |
|     11555 |
|     11569 |
|     11578 |
|     11581 |
|     11585 |
+-----------+

**Comment by katrialesser** [comment]
Joe's people will take a look at these

i.e.
news.byu.edu/node/10289
news-linux.byu.edu/node/10289

**Comment by katrialesser** [comment]
Note: The stories to look at will likely be those above PLUS some of the new 2018 stories. @sher1 can probably post a new updated list here for Joe's people to go off of.

**Comment by sher1** [comment]
Here is the new list

SELECT entity_id FROM `node__body` WHERE body_value like '%[[{"fid":"%'

 Showing rows 0 - 137 (138 total, Query took 0.1615 seconds.)

entity_id	
10289	
10740	
10770	
10799	
10800	
10854	
10864	
10882	
10939	
10998	
10999	
11005	
11012	
11019	
11020	
11032	
11036	
11043	
11046	
11054	
11057	
11058	
11060	
11061	
11068	
11073	
11078	
11079	
11108	
11109	
11113	
11118	
11128	
11130	
11159	
11161	
11165	
11178	
11182	
11185	
11187	
11193	
11199	
11209	
11227	
11228	
11229	
11233	
11239	
11240	
11241	
11245	
11246	
11247	
11249	
11252	
11255	
11260	
11262	
11317	
11352	
11363	
11367	
11369	
11370	
11375	
11376	
11377	
11378	
11380	
11395	
11399	
11402	
11412	
11414	
11435	
11454	
11455	
11457	
11466	
11469	
11476	
11480	
11481	
11484	
11485	
11493	
11494	
11503	
11504	
11506	
11512	
11515	
11526	
11530	
11536	
11555	
11569	
11578	
11581	
11585	
11590	
11608	
11613	
11638	
11639	
11647	
11649	
11673	
11678	
11679	
11680	
11684	
11685	
11687	
11690	
11692	
11700	
11703	
11704	
11706	
11707	
11712	
11722	
11730	
11733	
11737	
11743	
11746	
11753	
11761	
11766	
11769	
11774	
11778	
11779	
11787	
11789

**Comment by TDW88** [comment]
I am going through these now and found that 11608 and down give a "The requested page could not be found." error Message.

**Comment by sher1** [comment]
Here are the ones that are left
10289
10770
10864
10882
10999
11054
11130
11159
11187
11227
11239
11247
11480
11608
11613
11692
11700
11703
11704
11706
11707
11712
11722
11730
11733
11737
11743
11746
11753
11761
11766
11769
11778
11779
11787
11791

**Comment by TDW88** [comment]
On it

**Comment by blakemorgan** [comment]
10289: This website encountered an unexpected error
10770: 404
~~10864~~
~~10882~~: Test story
~~10999~~
~~11054~~: Never published
~~11130~~
~~11159~~
~~11187~~
~~11227~~
~~11239~~
~~11247~~: Test story
~~11480~~
~~11608~~
~~11613~~
~~11692~~: Test story
~~11700~~
~~11703~~
~~11704~~
~~11706~~
~~11707~~
~~11712~~
~~11722~~
~~11730~~
~~11733~~
~~11737~~
~~11743~~
~~11746~~
~~11753~~
~~11761~~
~~11766~~
~~11769~~
~~11778~~
~~11779~~
~~11787~~
11791
