### ISSUE TITLE
review theme adjustments for byu theme, approve theme release and put this site on it

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#120]
- [x] review theme adjustments for byu theme, 
- [x] approve theme release and 
- [x] put this site on it
- [x] test through changes (mostly body classes)

**Comment by katrialesser** [comment]
it causes this issue on our site - blank page and error:
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">InvalidArgumentException</em>: $string (&quot;&quot;) must be a string. in <em class="placeholder">Drupal\Core\StringTranslation\TranslatableMarkup-&gt;__construct()</em> (line <em class="placeholder">133</em> of <em class="placeholder">core/lib/Drupal/Core/StringTranslation/TranslatableMarkup.php</em>).

I made some tweaks and William is looking through trying to see where the issue could be coming from.

William is going to be debugging with byu_theme and our byu news subtheme.

**Comment by masterqwerty** [comment]
It seems there was a quotation mark that was missing in one of the templates, which was causing some problems. However, I don't know if this is the cause of the error.
