### ISSUE TITLE
Review and improve responsive video code

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#121]
See if there's a better way to do this - particularly to avoid using position: absolute whenever possible, and to see if there's a cleaner way to do the padding-bottom 

.video-responsive {
  //overflow:hidden;
  padding-bottom:56.25%;
  position:relative;
  //height:0;
}
.video-responsive iframe {
  height:100%;
  width:100%;
  position:absolute;
}

**Comment by masterqwerty** [comment]
```
.video-responsive {
  position: relative
}

.video-responsive iframe {
  height: 100%;
  width: 100%;
}
```
It seems that without both of the options, the div is about 4 pixels taller, but still looks just about the same. In fact, it appears that `position: relative` was only there so `position: absolute` could be used, so the rule for `.video-responsive` isn't needed. All that we really need are the `height` and `width` options for the rule with the `iframe`, which resizes the video to be the necessary size.
