### ISSUE TITLE
Transfer API over

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#13]
Migrate the API and its features to the new site. We'll have to change how we do this since the service view module isn't for Drupal 8.

**Comment by blakemorgan** [comment]
Trying to use the RESTful API module, but getting an error when I try and access the page.

**Comment by katrialesser** [comment]
We will likely stay on 8.4 until they release a fix for this issue with 8.5

**Comment by katrialesser** [comment]
Also 
Add API for top story (one in hero on homepage)
*Mobile app could then pull it in..

**Comment by blakemorgan** [comment]
The site ended up getting upgraded. I don't know how, but a workaround for the error is to add `?_format=json` to the end of the URL, then it will work. Will that affect anyone consuming the API already?

**Comment by blakemorgan** [comment]
Turns out this was a noted change in the Drupal core change records (see https://www.drupal.org/node/2954953). We will need to create redirects from old endpoints to new endpoints with the `?_format=json` or `?_format=xml` parameter.

**Comment by katrialesser** [comment]
Sherwin will come back with how you can set up in views to do .xml or .json 

We would just have to redirect without any .json or .xml and redirect it to .xml for current users.

**Comment by blakemorgan** [comment]
### Issues in migrating the API
- Because we got rid of the person content type, Drupal doesn't know what to link to for `writerName` so it just returns `null`

**Comment by blakemorgan** [comment]
Migrating the API is complete. The news components just need to be updated.

**Comment by blakemorgan** [comment]
The news components have been updated. The API documentation needs to be updated in the news components repo. I will make that an issue there.
