### ISSUE TITLE
amp theme isn't working on mobile story pages on news-dev

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#130]

**Comment by katrialesser** [comment]
We confirmed on friday june 8th that it wasn't working/showing/in use for mobile story pages.

**Comment by sher1** [comment]
This website verified that amp is not working
https://search.google.com/test/amp?id=I8ZigASf6hza59fpd0rnNQ
Not sure whether we should put effort into this or not

**Comment by sher1** [comment]
Actually, I just checked the configuration and it is only set up for stories. Those appear to be valid, closing

**Comment by sher1** [comment]
https://search.google.com/test/amp?skip_amp_follow=true&id=Octuaby2XfibhKnUv7mOAw
