### ISSUE TITLE
Make sure Search is working - wasn't working at all for me just now

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#136]
Tried many common words like 'students' 'devotional' 'amanda knight'/'allen hall' for a specific story. Capitalization doesn't seem to matter, and I never get any results.

**Comment by katrialesser** [comment]
Sherwin's update - this is because the content hasn't been re-indexed, which we weren't going to have start until we were sure this was the last migration. I believe we are ready to re-index.

**Comment by sher1** [comment]
We have re-indexed everything and the search works great
