### ISSUE TITLE
Add redirect module and add any necessary redirects.

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#138]
This module is crucial for whenever a story's title change, it will automatically add redirects so links don't break. We also need it for anytime we want to add custom redirects.

Recent stories with different urls on production than on our new news-dev:

http://news.byu.edu/news/byu-announces-2018-19-theatre-season
http://news.byu.edu/news/byu-students-finalists-e3-game-competition
http://news.byu.edu/news/study-today%E2%80%99s-dads-are-engaging-more-their-kids
http://news.byu.edu/news/byus-best-best-social-media-content-recognized-6th-annual-byu-golden-hashtags
http://news.byu.edu/news/tackling-fatal-disease-chemistry
http://news.byu.edu/news/how-get-people-pay-attention-phone-computer-security-notifications
http://news.byu.edu/news/anne-green-gables-still-inspires-audiences-byu-production
http://news.byu.edu/news/cougar-query-randal-beard
http://news.byu.edu/news/one-weird-trick-lands-students-major-social-media-experience
http://news.byu.edu/news/laura-benanti-pixar%E2%80%99s-coco-and-cirque-eloize-headline-byu%E2%80%99s-diverse-2018-2019-bravo-0
http://news.byu.edu/news/byu-professor-leading-video-based-research-methods
http://news.byu.edu/news/cougar-query-1
http://news.byu.edu/news/byu-addresses-all-23-recommendations-eliminate-sexual-assault-and-approves-updated-sexual
http://news.byu.edu/news/rob-barrett-cougar-query-you%E2%80%99ll-never-find-me-without-drawing-and-painting-supplies-nearby
http://news.byu.edu/news/byu-womens-conference-general-relief-society-counselors-share-examples-ministering
http://news.byu.edu/news/byu-womens-conference-president-worthen-teaches-about-inspired-ministering
http://news.byu.edu/news/byu-women%E2%80%99s-conference-following-christ%E2%80%99s-pattern-love
http://news.byu.edu/news/chevron-phillips-chemical-teams-byu-researchers-reduce-catalyst-development-time
http://news.byu.edu/news/byu-broadcasting-doubles-down-byuradio-utah-purchase-agreement-radio-station-utah
http://news.byu.edu/news/early-diagnosis-catalyst-student-music-career
http://news.byu.edu/news/elder-holland-speak-april-graduation-commencement-ceremony
http://news.byu.edu/news/extraordinary-geological-adventures-new-byu-grad-hannah-bonner
http://news.byu.edu/news/byu%C2%A0names-new-chief-information-security-officer
http://news.byu.edu/news/byu-devotional-ministering-holier-way
http://news.byu.edu/news/students-build-hand-trike-attachment-lds-charities-global-wheelchair-initiative
http://news.byu.edu/news/byu-womens-conference-be-held-may-3%E2%80%934

There may be others as well - these are just about the last 3 months' worth.

I've added the module, but we won't have automatically-migrated redirects from the past unless we redo the migration.

I don't know if this is a priority; I've checked through a couple months and just found a handful. I'm happy to go through a few more months' worth of stories (won't take too long) and check for any that need a redirect added.
I think that we could keep an eye on the report of broken/missing links and fix any that emerge as an old link that someone is using, and add the appropriate redirect.

**Comment by katrialesser** [comment]
Alright, so in 3 months' of stories there were like 25 urls that didn't match up. I think it's safe to guess that we have plenty of stories that have had their stories changed at some point and didn't have the redirect module going on the d7 site, so the urls don't match up.. 
I think we need to bring over redirects. @lujieh  does that mean we'd need to re-run the script or is there a way we can add redirects without it?
Something like:
For each node, get url alias from production, add it as a redirect for that node on news-dev.

If we can write a script to add them and resave the existing nodes it'd save me having to redo the work

**Comment by katrialesser** [comment]
If we do have to re-run the migration script, I'll look at which issues I closed today and i can easily re-do my work after that.
so I guess it just depends on what's the best way to bring over all url aliases and redirects.

I've installed the redirect module, although if Julie resets the database, she'll need to re-enable it before we do the migration script. Or, a new script that just adds the redirect without redoing the entire migration.

From all my testing, all the fields are in place and everything looks good except for redirect urls.

**Comment by sher1** [comment]
These are done although we will need to do it again when we do the final import

**Comment by sher1** [comment]
Removing the redirects, something is wonky, although the story might be bad

**Comment by katrialesser** [comment]
What do you mean when we do the final import? I didn't think we were going to do the migration over again?

**Comment by sher1** [comment]
Things are fine now, we will need to run this again to get any additional redirects for stories that have been added since we did the migration

**Comment by katrialesser** [comment]
weve looked at this issue a lot and won't be automatically doing something to rectify discrepancies in different url aliases. I will go through and add redirects manually for these stories (3 months back worth) plus all title ix stories, and i may check back a little farther for good measure.

**Comment by katrialesser** [comment]
i am going to manually add redirects for all stories above and all title ix stories, and possible check back a bit further. this list above is about 3 months back, i will go through these tonight/tomorrow.

1. Okay, so i think the best option is to go to the main redirects page, click add redirect. https://news-dev.byu.edu/admin/config/search/redirect
2. open the production story from the issue i posted and copy the url section from news/ on
3. in the add redirect tab, add from the path we are using on news PRODUCTION i.e. news/byu-announces-2018-19-theatre-season
4. and to the node id - check the nid editing the production story and add `/node/12345` or i.e `/node/11740`
This will add the redirect without having to edit the story (which is slow due to required fields and field changes on migrated stories) but then it WILL add this redirect onto the node and you can see it working if you edit the node on news-dev.
I am fine adding all of these tonight/tomorrow for those stories and checking all the title ix ones.
it won’t take too long for me to do them all, probably 15-30 minutes

**Comment by sher1** [comment]
I have added the ones above. We still need to see if there are additional ones to add.

**Comment by sher1** [comment]
This is being done as Blake requested, adding redirects as they are found
