### ISSUE TITLE
Get space styling working again with in-story aligned images

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#141]
Do we know if anyone has changed or adjusted the ckeditor settings? The classes that were in use before (`align-left` `align-right` `align-center`) are not in use anymore so my spacing styling isn't working now for images inside stories.

It's just putting inline styles `float: left` or `float: right` now, so i can't set the margin conditionally based on the alignment..
But this was working before.

We could put margin: 20px on all images, but then left-aligned won't line up nicely with the edge of text on the left, or right-aligned line up with the right edge of text nicely.. that's what i had working before.

**Comment by katrialesser** [comment]
update: it's only migrated inline images that don't work. adding new images uses the classes correctly.

this story currently has a migrated story and then the same image added in by me manually. (and sized manually in code in another field.. which isn't an option right now with the Very Basic html text format. might have to temporarily enable the source button while #86 is still an active issue.
https://news-dev.byu.edu/news/stopping-tiny-and-deadly-fly-its-tracks

migrated image not working right:
<p><img alt="" height="265" src="/sites/default/files/1807-09%2003.JPG" style="float:left" width="400"></p>

newly added image, working right:

<p><img alt="Professor in lab" data-entity-type="" data-entity-uuid="" src="/sites/default/files/1807-09%2003.JPG" style="width: 400px" class="align-left"></p>

**Comment by katrialesser** [comment]
@sher1 @lujieh how horrible would it be to run a script that adjusted the images formatted like the top to formatted like the new correct format below?

**Comment by sher1** [comment]
It would be problematic. Where would we get the alt tag from? If all we wanted to do was swap the style tag with the class tag and add the data-entity-uuid tag, that might work

**Comment by katrialesser** [comment]
Update: we are doing even margin all around on images that don't have alignment set (migrated inline images) and then the most ideal margin styling will still work for the new stories' inline images with alignment setting. it won't require much time and things will look fine.

**Comment by katrialesser** [comment]
After pr is merged, test and make sure on this story:
https://news-dev.byu.edu/news/stopping-tiny-and-deadly-fly-its-tracks

and then check around on other stories.

**Comment by katrialesser** [comment]
looks like it is applying properly now for migrated images and new images. :)

**Comment by sher1** [comment]
This has broken the styling of the related stories. I will either get more specific with this one or figure it out for the other one

**Comment by sher1** [comment]
made the style more specific to target only inline images in the body
