### ISSUE TITLE
Image uploading is poor UX

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#177]
There is a choose file button and an open file browser button.

**Comment by blakemorgan** [comment]
WE need both so users can access image on the server.

**Comment by blakemorgan** [comment]
Talk to @hadfieldjoe about whether he wants it hidden where not needed.

**Comment by blakemorgan** [comment]
He says if we can hide it where it isn't needed (the thumbnail and meta image field) he'd like that.

**Comment by blakemorgan** [comment]
@hadfieldjoe We are able to do this, but then writers and editors won't be able to reuse images already on the server in those fields. What would you like?

**Comment by hadfieldjoe** [comment]
That is fine to not be able to reuse old images on the server. BUt we do have a problem today with text not wrapping on inline images.

**Comment by blakemorgan** [comment]
Text image wrapping was because there were attributes getting strippe out of the HTML img tag. I have fixed that.
