### ISSUE TITLE
Downloadable photos don't upload

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#178]
After slecting a file to be upload to the downloable photos field, nothing happens. Maybe an error is occuring, but it is not displayed.

**Comment by blakemorgan** [comment]
There is no issue with the field settings, which makes me think it is either a server, PHP, or AJAX error.

**Comment by blakemorgan** [comment]
Fix in server conf

**Comment by sher1** [comment]
This was added to the site conf file (news.conf)
# set client body size to 256M #
client_max_body_size 256M;
under the root line
