### ISSUE TITLE
Send a story has issues

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#186]

**Comment by sher1** [comment]
What are the issues?

**Comment by blakemorgan** [comment]
Great question. I forget. I'm waiting for Joe to get back so I can ask him.

**Comment by blakemorgan** [comment]
![screenshot from 2018-09-07 10-41-44](https://user-images.githubusercontent.com/9389424/45231814-a481c880-b28a-11e8-8ae5-a808f1fad1e3.png)
@sher1 Do you think this has something to do with how the server is set up?

**Comment by sher1** [comment]
the smtp server needed to be changed to xinetd-managed.aws.byu.edu port 587
