### ISSUE TITLE
Homepage Hero

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#2]
Rather than the text is on top of the image, Joe wants it on the side (a la old BYU homepage hero).

**Comment by hadfieldjoe** [comment]
We're junking the masthead images for the story pages and for the front page. 

The desktop front page should have a single large, 16x9 dimension image with preview text spaced to the right. Then the list of recent front-page articles will follow below.

**Comment by katrialesser** [comment]
front photo display
photo bigger than the small feature rows with text on the right
come up with specs and talk to Joe

Significantly bigger than
16 x 9 ratio or close
Not too much vertical space
We'll have white space to the right of this feature
And not have the right column blocks go up all the way to the top

**Comment by katrialesser** [comment]
Joe approves, will build this into the hero component.

**Comment by katrialesser** [comment]
Also, I will work with the community to help build the drupal 8 hero module so there is a nice interface.

**Comment by katrialesser** [comment]
Specs for Image / Youtube video: 
Desktop: 570px wide, 320px tall
Text to the right would adjust based on parent container / page width.
Ipad landscape: 
A) Image same size, text to the side (will check this in implementation)
B)  adjust image size down to 270px tall, 480px wide

Ipad portrait version: Image goes down to 180px tall x 320px wide, text to the side still.
Mobile version (below 768px): Image will stretch full width, text displayed below the image.

**Comment by katrialesser** [comment]
Created a pull request to add this style in to the hero component:
https://github.com/byuweb/byu-hero-banner/pull/24

**Comment by blakemorgan** [comment]
Not responsive. 
![screenshot from 2018-05-08 17-51-08](https://user-images.githubusercontent.com/9389424/39788618-7be235e2-52e8-11e8-8d4d-90bbca7e84b7.png)

**Comment by blakemorgan** [comment]
Font needs to be changed to Sentinel and Ringside.

**Comment by katrialesser** [comment]
The homepage hero itself is done
The responsive issues are due to content region issues, which is in another issue. 
- [ ] blake can you change the main body text in the hero components ringside instead of gotham and submit a PR?
Then i think we can mark this off.

**Comment by katrialesser** [comment]
i submitted a pr for this so it can be merged by kevin. Everything else done for hero!
