### ISSUE TITLE
Identify which stories use slideshow, adjust them after migration

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#23]
One example:

http://news.byu.edu/news/byu-wins-national-landscape-competition-landslide

**Comment by blakemorgan** [comment]
Will be done with a database query.

**Comment by katrialesser** [comment]
- [ ] Sherwin do sql query for the token, find how many there are and which nid's
- [ ] look at one that is migrated, see how broken
- [ ] manually fix those stories (AFTER content migration)

**Comment by sher1** [comment]
Here are the 43 nodes that this affects

10264
10288
10293
10530
10667
10728
10738
10740
10773
10790
10794
10802
10803
10806
10813
10820
10821
10822
10825
10827
10833
10839
10842
10851
10874
10876
10880
10881
10886
10932
11003
11061
11126
11160
11324
11349
11362
11419
11443
11514
11532
11607
11664

**Comment by katrialesser** [comment]
Will need to check for new nid's/re-generate this list. but for example:
http://news-dev.byu.edu/node/11003/edit
has
[views:embed:story_page_slideshow]

**Comment by sher1** [comment]
New list of nodes with slideshows:
10264	
10288	
10289	
10293	
10530	
10667	
10728	
10738	
10740	
10770	
10773	
10790	
10794	
10799	
10800	
10802	
10803	
10806	
10813	
10820	
10821	
10822	
10825	
10827	
10833	
10839	
10842	
10851	
10854	
10864	
10874	
10876	
10880	
10881	
10882	
10886	
10932	
10939	
10998	
10999	
11003	
11005	
11012	
11019	
11020	
11032	
11036	
11043	
11046	
11054	
11057	
11058	
11060	
11061	
11068	
11073	
11078	
11079	
11108	
11109	
11113	
11118	
11126	
11128	
11130	
11159	
11160	
11161	
11165	
11178	
11182	
11185	
11187	
11193	
11199	
11209	
11227	
11228	
11229	
11233	
11239	
11240	
11241	
11245	
11246	
11247	
11249	
11252	
11255	
11260	
11262	
11317	
11324	
11349	
11352	
11362	
11363	
11367	
11369	
11370	
11375	
11376	
11377	
11378	
11380	
11395	
11399	
11402	
11412	
11414	
11419	
11435	
11443	
11454	
11455	
11457	
11466	
11469	
11476	
11480	
11481	
11484	
11485	
11493	
11494	
11503	
11504	
11506	
11512	
11514	
11515	
11526	
11530	
11532	
11536	
11555	
11569	
11578	
11581	
11585	
11590	
11607	
11608	
11613	
11638	
11639	
11647	
11649	
11664	
11673	
11678	
11679	
11680	
11684	
11685	
11687	
11690	
11692	
11700	
11703	
11704	
11706	
11707	
11712	
11722	
11730	
11733	
11737	
11743	
11746	
11753	
11761	
11766	
11769	
11774	
11778	
11779	
11787	
11789

**Comment by sher1** [comment]
Here are the 44 ones with slideshow
SELECT entity_id FROM `node__body` WHERE body_value like '%views:embed:story_page_slideshow]%'

entity_id	
10264	
10288	
10293	
10530	
10667	
10728	
10738	
10740	
10773	
10790	
10794	
10802	
10803	
10806	
10813	
10820	
10821	
10822	
10825	
10827	
10833	
10839	
10842	
10851	
10874

**Comment by katrialesser** [comment]
@sher1 there are only 25 nid's, looks like this isn't the full nid list, can you check that? It should be the first nid list plus probably 1 recent story..

**Comment by katrialesser** [comment]
Alright, I have fixed and adjusted all of the stories on the first long list to use our new fields and have the correct slideshow setup. We just need to fix the last new one that I need a nid for. If you run your script Sherwin, there is probably only one that will return now.

**Comment by sher1** [comment]
One left: 11774

**Comment by katrialesser** [comment]
Alright, adjusted the last nid sherwin gave me, all of these are done!
