### ISSUE TITLE
Make entire story preview region clickable on front page

### ISSUE THREAD

**Issue by hadfieldjoe** [byu-oit/news-website#24]
Right now only the title is clickable.

**Comment by blakemorgan** [comment]
@hadfieldjoe The image and category are also clickable. The description is the only thing that isn't clickable. I can probably make that clickable, but not the whole area; is that OK?

**Comment by blakemorgan** [comment]
Correction: fixed in 8a82a8de380ce47cf7bb3fa14cb4a08d7754cb71

**Comment by blakemorgan** [comment]
Javascript and CSS needs to be updated since we aren't using the paragraph anymore. Waiting for #61 and #2 to be completed before finishing.
