### ISSUE TITLE
Additional Pages

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#26]
Needs Terms of Use and Title IX pages added

**Comment by hadfieldjoe** [comment]
on the list of Title IX stories, need the ability to pin one or more stories at the top of the list. Others can flow in chronology based on the tag.

**Comment by blakemorgan** [comment]
Rolled back database and lost changes. Need to recreate

**Comment by blakemorgan** [comment]
Fixed in 665cb86
