### ISSUE TITLE
Add Most Read Stories block onto story pages - goes bottom of right rail

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#28]
No images, style after the one on fox news

http://www.foxnews.com/

**Comment by blakemorgan** [comment]
Fixed in 57c3e4edd90591c24f4ba2133cf56c8712d932de

**Comment by blakemorgan** [comment]
Only fixes the first story. Others link to the first story rather than their own.

**Comment by blakemorgan** [comment]
Got it working if the story has photos. Will there ever be a story without photos?

**Comment by blakemorgan** [comment]
Only about 80% of the stories will have photos, so we need to display it in a way that works when a story doesn't have photos.

**Comment by hadfieldjoe** [comment]
The time frame should be most popular stories in the past month/30 days.

**Comment by blakemorgan** [comment]
Had to rool back the database. Need to import the block config

**Comment by sher1** [comment]
This is blank on news-dev and news-linux

**Comment by sher1** [comment]
fixed by Blake
