### ISSUE TITLE
Configure roles

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#35]
Configure permissions and role. Correctly assign current users to their proper role.

**Comment by blakemorgan** [comment]
This is configuring all roles making sure things work with new features.

**Comment by blakemorgan** [comment]
I'm going to reassign this to @katrialesser and @sher1 because they're the ones who, when this site is in production, will care most about what people can and cannot do.

**Comment by sher1** [comment]
did these with Blake
