### ISSUE TITLE
Share button pre-populates a tweet with page title, not story title

### ISSUE THREAD

**Issue by hadfieldjoe** [byu-oit/news-website#37]
![image001](https://user-images.githubusercontent.com/12865535/39328337-4bf97afa-4958-11e8-8638-811a5361367c.png)

**Comment by blakemorgan** [comment]
we want Share buttons for Facebook Twitter LinkedIn and G+. The current D7 news site has Facebook Twitter G+ Email and comment.

**Comment by blakemorgan** [comment]
Got it fixed. The ShareThis buttons are different than the buttons in the footer. @hadfieldjoe Do you want them to be the same?

**ShareThis**
![screenshot from 2018-04-30 17-14-28](https://user-images.githubusercontent.com/9389424/39454970-5f45b22c-4c9b-11e8-9df8-f2bde975e537.png)

**Footer**
![screenshot from 2018-04-30 17-14-39](https://user-images.githubusercontent.com/9389424/39454982-67eacbce-4c9b-11e8-92bd-50cc3528777e.png)

**Comment by blakemorgan** [comment]
Fixed in 3625c56930d6da8c9156bc6da8a27fd809be1f8b
