### ISSUE TITLE
check through all views and make sure they have the right fields

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#39]
i.e. summary field AND old body's summary section
- [x] ANY BODY FIELD - MAKE SURE IT HAS BOTH: old - body's summary, new - summary field
- [x] old - highlights field, new - highlight is a section in the main body (i know this isn't in any views actually) - TELL US IF THERE ARE ANY THAT USE IT

- [x] old - was a publicized field that wasn't brought over, new - has publicized - sherwin needs to do script before you can test this one

check any view settings for using the is publicized checkbox

**Comment by katrialesser** [comment]
Basically we have to test that it works with an old story (with content in the old body field and highlights field)
And with new stories (Which use paragraphs "main body" field, summary field

**Comment by arzon94** [comment]
Check API views for publicized field

- [ ]

**Comment by blakemorgan** [comment]
- [ ] Export paragraphs body as single field in Story API.
