### ISSUE TITLE
Attempt to create a field field_link that does not exist on entity type node.

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#52]
Temporary workaround: created a field `field_link` on the Person content type that is no longer used. we need to figure out why this is happening and find a permanent solution.

**Comment by katrialesser** [comment]
- [ ] new content type with this field
- [ ] hide permissions so no one sees this content type

**Comment by blakemorgan** [comment]
Deleted field, but field still exists. Revisit in 24 hours.

**Comment by blakemorgan** [comment]
Created missing tables. `drush eval "field_purge_batch(500)"` no longer throws and error.
