### ISSUE TITLE
Use BYU paragraph types on random pages

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#64]
The Title IX, Terms of Use, and other pages use Bootstrap paragraphs. We need to use our own paragraphs so we can get rid of Bootstrap paragraphs.

**Comment by katrialesser** [comment]
- [ ] title IX
- [ ] Terms of Use
- [ ] others

**Comment by katrialesser** [comment]
this issue related to https://github.com/byu-oit/news-website/issues/127

**Comment by sher1** [comment]
These were just re-created without the bootstrap paragraphs
