### ISSUE TITLE
Fix the search

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#7]
The search bar needs to search the body of stories as well as the titles.

**Comment by hadfieldjoe** [comment]
The article body is not searchable for any content created since the launch of the D7 site. Articles that had been migrated in are searchable. 
Test case: Search for "Kamalu" and see if it returns the story about Jordan Kamalu winning a student emmy for music composition.

**Comment by sher1** [comment]
I just searched for percent which shows up a bunch but I found a few articles on the 2nd page of results that have percent in the body but not the title.

**Comment by sher1** [comment]
Russon shows up in the search but Kamalu which is in the same article, does not

**Comment by blakemorgan** [comment]
We will just be using the basic search for now. Phase two will be integrating the search API and maybe Solr?
