### ISSUE TITLE
Image alignment and resizing

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#86]

**Comment by blakemorgan** [comment]
Known bug in core. Applied this patch: https://www.drupal.org/files/issues/2018-03-29/2822217-drupalimagecaption-img-src-fix-13.diff

**Comment by katrialesser** [comment]
This is no longer working - @sher1 perhaps this patch is not being applied correctly anymore.

**Comment by katrialesser** [comment]
@sher1 you had said that it worked when you applied it locally right?

Let me know when you have this fixed again on news-dev and i'll help test around and confirm it looks like it's working everywhere.

I want to particularly test and check a migrated image as well as a newly-added image.

**Comment by sher1** [comment]
I have patched it but I am not sure how to test this

**Comment by katrialesser** [comment]
I found a story that was migrated with an inline image, and confirmed that resizing/moving/editing captions all works great now. thanks!
https://news-dev.byu.edu/node/11774/edit
