### ISSUE TITLE
Instagram caption embedding doesn't work in social media embed - that part is trimmed?

### ISSUE THREAD

**Issue by katrialesser** [byu-oit/news-website#88]

**Comment by blakemorgan** [comment]
The instagram code is getting parsed into a iframe even though the embed code isn't an iframe.

**Comment by katrialesser** [comment]
example public instagram post to test with:
https://www.instagram.com/p/Bhw213NgpnI/

embed > use caption

paste embed code into the social media paragraph type when adding a story to test.

**Comment by masterqwerty** [comment]
It seems that the div before the iframe could be trimming the iframe. The weird thing is that if you change the div's bottom padding to 100%, it will show the entire iframe. The bottom padding by default is 56.25%. Is this supposed to be that way?

**Comment by katrialesser** [comment]
William removed the class and tested twitter, instagram and facebook videos and all work great without that class; I don't know why it was added with all that css to start with. Youtube videos are in the video paragraph type. This is fixed now with that css removed.
