### ISSUE TITLE
Improve UI to send alerts

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#9]
Currently, we are using a webform and conceptually this approach should work well. I need help figuring out how to send to email addresses listed as an option in the webform.

**Comment by katrialesser** [comment]
Simple to send out a story
Simple to update the directory list

Button 'Share This Story' for editors only -> goes to webform with pre-selecting the entity reference??
And look at entity embed options like I did for support issue content type, embedding things (especially for editing list of directory)

**Comment by blakemorgan** [comment]
UPDATE: Address book taxonomies have been migrated over and views send does what we need to, We just need to change the email form.

**Comment by katrialesser** [comment]
I have gotten a working setup on a local site. We can show this to Joe tomorrow and make sure that that works for him.
I am trying to confirm that token support works also.
I can put this on our actual site once we resolve the other issues.

**Comment by katrialesser** [comment]
- [ ] make sure it works with actual mailing
- [ ] check styling in email
- [ ] Andy is working on styling the interface checkboxes #80

**Comment by katrialesser** [comment]
Also allow up to 30 recipients at once,
Improved checkboxes and formatting
full html except images
Need to have Joe check how things are looking and give approval / feedback etc.

**Comment by katrialesser** [comment]
- [ ] Need to remove or fix images

**Comment by katrialesser** [comment]
I think I can use twig in the email body if we switch to the dev version of webform; that was a feature added into the dev version 5 months ago.

**Comment by katrialesser** [comment]
it wasn't a duplicate title; that was the subheading.

**Comment by katrialesser** [comment]
Removed images properly.
