### ISSUE TITLE
Redirect ucom.byu.edu to contact us page

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/news-website#94]

**Comment by arzon94** [comment]
after discussing with Mike, we will wait till the news site is published to news.byu.edu, nslookup the ip and use quip to redirect ucom.byu.edu. We could get on typo1.byu.edu and set up a redirect on the server, but he thinks it makes more sense to shut down the ucom.byu.edu site and use quip to resolve the ucom domain

**Comment by blakemorgan** [comment]
We need ucom.byu.edu to go to news.byu.edu/contact-us. You cannot redirect to a path in qip.
