### ISSUE TITLE
Password setting for creating new user account

### ISSUE THREAD

**Issue by hadfieldjoe** [byu-oit/news-website#97]
This may or may not matter, but when I create a new account for someone on news-linux, it requires me to enter a password. This system should be using CAS, so it's unnecessary for me to create a password, right?

**Comment by blakemorgan** [comment]
Thats just how Drupal 8 works. Just create a random password. As long as you add their CAS username, they'll never need to use the fake password you created. They'll always be dirceted to CAS.
